### ISSUE TITLE
Make it clear we should directly commit to the website

### ISSUE THREAD

**Issue by KnowsCount** [elrumo/macOS_Big_Sur_icons_replacements#1029]
Hi.. I see many opening pull requests, you might want to make sure they know we should commit it directly unto the website as you have stated multiple times before. Maybe add a some warning whatchamacallits into the README file?

Not necessary, but would make it easier for new-comers.

**Comment by elrumo** [comment]
Yeah, that's an issue that has already been raised [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/1039). In short, all icons submitted since early Jan won't have that issue, but older icons will. Hopefully soon I'll fix the the problem for old icons.
