### ISSUE TITLE
Zeplin white bg listed but cannot be downloaded

### ISSUE THREAD

**Issue by osrl** [elrumo/macOS_Big_Sur_icons_replacements#1033]
### Describe your issue here, and if possible, add an image.
Nothing happens when you click the icon. I also couldn't find it in the repo

<img width="536" alt="Screen Shot 2021-01-09 at 02 31 23" src="https://user-images.githubusercontent.com/781453/104075066-cc024a80-5222-11eb-99f2-72274bc40172.png">

**Comment by elrumo** [comment]
Should be fixed now, some icons weren't properly imported after the backend migration I did last month from Firebase to Parse

**Comment by osrl** [comment]
Keka Alt is also the same. I think backend needs a cleanup
