### ISSUE TITLE
Many icons grainy/low resolution when downloaded

### ISSUE THREAD

**Issue by jasonad123** [elrumo/macOS_Big_Sur_icons_replacements#1081]
### I've tried downloading a lot of icons recently and I'm finding many of them are quite grainy when downloaded and when loaded into an app as a result. It doesn't seem to be isolated to a few uploads either. 

I've uploaded the results from Finder for a few of my most recent downloads (Sketchup and the Unifi Controller).
![Screen Shot 2021-02-03 at 9 51 59 AM](https://user-images.githubusercontent.com/74881573/106788299-a12eca80-6605-11eb-9803-6be80c35f970.png)
![Screen Shot 2021-02-03 at 9 51 55 AM](https://user-images.githubusercontent.com/74881573/106788302-a25ff780-6605-11eb-8299-42a623a45900.png)

**Comment by elrumo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re export all png icons as .icns files to remove "blurriness"](https://trello.com/c/7i9xGzZw/43-re-export-all-png-icons-as-icns-files-to-remove-blurriness)

**Comment by elrumo** [comment]
The issue should be fixed for most icons now, although some might still remain, I'll fix them as I come across them.
