### ISSUE TITLE
Icon disappears again

### ISSUE THREAD

**Issue by Asored-D** [elrumo/macOS_Big_Sur_icons_replacements#1083]
I have some issues with the Chrome icon. It's fine for a few days, but after about a week, all I see is a folder icon. What can be the reason for this? Please check the attached image below.

![Bildschirmfoto 2021-02-05 um 10 37 15](https://user-images.githubusercontent.com/6883050/107016582-61e7b180-679e-11eb-9678-41115f738605.jpg)

BigSur 11.1
Chrome 88.0.4324.146

Thanks in advance for your help.

**Comment by bosconb** [comment]
same bug,any idea?

**Comment by drosa88** [comment]
... still no solution. It only appears with Chrome app...

**Comment by adan89lion** [comment]
It is observed that when an app is updated, the icon would disappear (and shown as a folder). You can go to "File Info" and click on the folder and hit `Backspace` to remove or replace the icon again.

**Comment by elrumo** [comment]
Closing this issue
