### ISSUE TITLE
Dead icon links

### ISSUE THREAD

**Issue by guidezpl** [elrumo/macOS_Big_Sur_icons_replacements#1088]
Certain icons have invalid links

e.g. Anki: http://82.145.63.160:1337/parse/files/macOSicons/4a77a633f454ed94cbcc36324a4efd14_Anki.icns
e.g. Antidote: http://82.145.63.160:1337/parse/files/macOSicons/e4c23b1454714326e3b3c3e8a6d68476_1606320367174_Antidote%2010.icns

**Comment by GGorAA** [comment]
idk, those links work for me

**Comment by guidezpl** [comment]
`$ ping: cannot resolve http://82.145.63.160:1337/parse/files/macOSicons/e4c23b1454714326e3b3c3e8a6d68476_1606320367174_Antidote%2010.icns: Unknown host`

**Comment by elrumo** [comment]
Thanks for raising it, I'm working on it and should be fixed soon

**Comment by elrumo** [comment]
I forgot to mention it, but I fixed those broken links and should be working fine. But do let me know if you spot any broken links again!
