### ISSUE TITLE
How do I revert back to the old icon?

### ISSUE THREAD

**Issue by SetuCoder** [elrumo/macOS_Big_Sur_icons_replacements#1117]
### I tried all the icons for photoshop but I felt the old was ok for me, so how do I revert back?

**Comment by SetuCoder** [comment]
This is not a todo!!!

**Comment by gl-Gho** [comment]
### 1
In a Terminal, type `rm -Rf /Applications/Application.app/Icon?` ( an app named 'My app' will be typed as  `My\ app.app` with a backslash before spaces. an `icon?` file contains the icon)
### 2
Choose the app from the **Applications** folder.
**File › Get info**
![](https://macosicons.com/img/getInfo.ee57e074.png)
Click on the small app icon on top so it is highlighted in blue
![Screenshot 2021-03-17 at 17 06 51](https://user-images.githubusercontent.com/80169337/111461949-d6b9ee00-8743-11eb-8f67-236312cc0493.png) 
On the keyboard, press on the ⌫ key (`Backspace` on any other or `delete` on an Apple keyboard)

**Comment by SetuCoder** [comment]
Ha thanks, works!
