### ISSUE TITLE
Social buttons and the "Back to Icons" Button overlap

### ISSUE THREAD

**Issue by AppChampion** [elrumo/macOS_Big_Sur_icons_replacements#1132]
When you go to the blog page, a "Back to Icons" Button is displayed. This button overlaps with the Twitter and Discord logos, making it hard to read.

<img width="1392" alt="Screen Shot 2021-04-02 at 9 40 56 AM" src="https://user-images.githubusercontent.com/65017752/113394277-39dc8f00-9398-11eb-82d7-c64c7e3bcb87.png">

**Comment by elrumo** [comment]
Yesterday I deployed a fix
