### ISSUE TITLE
Website is down :(

### ISSUE THREAD

**Issue by anton-patrushev** [elrumo/macOS_Big_Sur_icons_replacements#1143]

**Comment by anton-patrushev** [comment]
Still doesn't work for me :(

**Comment by elrumo** [comment]
What do you see when you visit the page?

**Comment by anton-patrushev** [comment]
@elrumo check this plz
https://drive.google.com/file/d/1jOCA5GTpc-pQOMixmJsmvN_lrnSv-DmE/view?usp=sharing

Seems like it's not able to be loaded (Idk, maybe there are some DNS issues with my region - BY)

**Comment by elrumo** [comment]
What country/region are you in?

**Comment by anton-patrushev** [comment]
BY - Belarus.
It's strange but it works from my phone internet (3G).
But it still doesn't work from my MacBook with WiFi.

**Comment by anton-patrushev** [comment]
@elrumo any updates here?

**Comment by elrumo** [comment]
I had a similar complaint some time ago from someone in Belarus, I am not sure what the problem could be but it seems to be related to that region in particular. If you access this URL, does it download an icon? [Download icon](https://media.macosicons.com/parse/files/macOSicons/9152bb59d1d22a6f14a4627b6ff84d88_LaCie_Rugged.icns)

**Comment by anton-patrushev** [comment]
@elrumo nothing happened

**Comment by elrumo** [comment]
It sounds like it could be some sort of regional block, the servers are in the UK, not sure if that could be having any impact on the block.

**Comment by elrumo** [comment]
Does the site work if you use a VPN and connect from another country?
