### ISSUE TITLE
Visual Studio Code and Docker

### ISSUE THREAD

**Issue by KZacharski** [elrumo/macOS_Big_Sur_icons_replacements#117]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Visual_Studio_Code.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Visual_Studio_Code.icns)<br>[Visual Studio Code](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Visual_Studio_Code.icns)

Done

VS Code is already on the list.
