### ISSUE TITLE
Misaligned content

### ISSUE THREAD

**Issue by aryanL-x86** [elrumo/macOS_Big_Sur_icons_replacements#1229]
### `Support this page`
![Untitled](https://user-images.githubusercontent.com/80169337/124268455-27205480-db57-11eb-8a7d-3af4bdc3cd3b.png)

                                                                                          ↑

**Comment by elrumo** [comment]
What browser do you use?

**Comment by elrumo** [comment]
Fixed: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/commit/c437a5771677f3ce7ba8ac6e78a3dcb24be20817
