### ISSUE TITLE
[Low Priority] Drop-down indicators

### ISSUE THREAD

**Issue by C47F15H** [elrumo/macOS_Big_Sur_icons_replacements#1230]
### Describe your issue here, and if possible, add an image.
![image](https://user-images.githubusercontent.com/80169337/124345355-0e1ab080-dbf6-11eb-8e21-6ca47191141b.png)
For adding a "v" shaped drop-down for 'Type of icon'

**Comment by elrumo** [comment]
Fixed, thanks for reporting: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/commit/96e0a06930de3327d30f807e4f58f25579d13cb2
