### ISSUE TITLE
Loading Icon On Icon Page Seems to be Buggy

### ISSUE THREAD

**Issue by theofficialgrand1** [elrumo/macOS_Big_Sur_icons_replacements#1242]
Uh...

https://user-images.githubusercontent.com/78011648/125064712-83e5b700-e0e3-11eb-9b32-10cb9eee4088.mov
found by @SetuCoder in the discord server

**Comment by elrumo** [comment]
Is the problem still present @theofficialgrand1 ? I could not replicate it.

**Comment by C47F15H** [comment]
It's ok (for me, now)
