### ISSUE TITLE
Problem with success sign

### ISSUE THREAD

**Issue by C47F15H** [elrumo/macOS_Big_Sur_icons_replacements#1248]
### There are two checkmark signs
![125193132-8d4c5c00-e268-11eb-86f8-4c59625ea5c2.png](https://user-images.githubusercontent.com/80169337/125193132-8d4c5c00-e268-11eb-86f8-4c59625ea5c2.png)
```
 ↑   ↑
```

**Comment by HimanshuVaghelaa** [comment]
@C47F15H  Assign this to me..

**Comment by elrumo** [comment]
> @elrumo  @C47F15H  Assign this to me..

I you can fix it, go for it!
