### ISSUE TITLE
Twitter issue

### ISSUE THREAD

**Issue by C47F15H** [elrumo/macOS_Big_Sur_icons_replacements#1255]
When a user does not choose a twitter account, instead of not showing a twitter icon at all in the user page, it exists and is a link that goes to @[undefined](https://twitter.com/undefined).

**Comment by elrumo** [comment]
I fixed it today with this [commit.](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/commit/f06e23218a3c406b7ff711e6aebcf1c095cc5d03)
