### ISSUE TITLE
Full-height icon containers

### ISSUE THREAD

**Issue by C47F15H** [elrumo/macOS_Big_Sur_icons_replacements#1260]
An image of it:
![screenshot](https://user-images.githubusercontent.com/80169337/126326128-00c115c7-6d62-49e7-bd7d-8fd89c84ab10.png)
The error in the console:
![screenshot_firefox_comsole](https://user-images.githubusercontent.com/80169337/126326124-1de97ad3-8bd9-45cc-a410-a16a0d27e60e.png)
Info | Info
--|--
OS | Mac OS 11.4
Browser | Mozilla Firefox 90.0

**Comment by elrumo** [comment]
Should be fixed, it was an issue with Firefox, thanks.
