### ISSUE TITLE
Icons arent loading.

### ISSUE THREAD

**Issue by Soft-Bred** [elrumo/macOS_Big_Sur_icons_replacements#1284]
### Icons aren't loading. Idk if this is due to any server issues.

The site says "There's a technical issue with the server and I'm currently away on holiday until next week. Apologies for any inconvenience caused"

Though idk when this was setup, and I haven't seen anyone with the same problem.

![](https://cdn.upload.systems/uploads/ibqXYPGy.png)

**Comment by C47F15H** [comment]
https://github.com/elrumo/macOS_Big_Sur_icons_replacements/discussions/1281
