### ISSUE TITLE
Wrong Dates at Popular section

### ISSUE THREAD

**Issue by Gregor-zbjk** [elrumo/macOS_Big_Sur_icons_replacements#1287]
### Describe your issue here, and if possible, add an image.

Hello, I have noticed that the Icons at the "Popular" section have a wrong Date.. It shows me that most of the icons in this section are uploaded or created at **1970**... and that's not possible because at this time was the internet present.

<img width="1680" alt="Bildschirmfoto 2021-09-11 um 15 13 23" src="https://user-images.githubusercontent.com/62333860/132949536-c51d4229-7d4d-49ec-b70c-a2d8886924c2.png">

**Comment by elrumo** [comment]
Those icons were submitted before there was no website and everything was GitHub based, so I don't have the dates for those icons. It's displaying 1970 because that's day 0 of the [UNIX time](https://en.wikipedia.org/wiki/Unix_time).
