### ISSUE TITLE
Firefox (and Firefox Developer Edition)

### ISSUE THREAD

**Issue by plusparth** [elrumo/macOS_Big_Sur_icons_replacements#13]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Firefox.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Firefox.icns)<br>[Firefox](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Firefox.icns)  

Firefox is done, I still need to make one for Firefox Dev

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Firefox_dev.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Firefox_dev.icns)<br>[Firefox_dev](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Firefox_dev.icns)

And here's Firefox Dev

**Comment by didacta** [comment]
Could you please make one for Firefox Nightly also? Thanks!
