### ISSUE TITLE
I cannot see the page

### ISSUE THREAD

**Issue by WillypaDJ** [elrumo/macOS_Big_Sur_icons_replacements#1307]
### Discussed in https://github.com/elrumo/macOS_Big_Sur_icons_replacements/discussions/1306

<div type='discussions-op-text'>

<sup>Originally posted by **WillypaDJ** October 24, 2021</sup>
![Captura de pantalla 2021-10-24 a las 21 19 44](https://user-images.githubusercontent.com/93095036/138609358-bb654c2e-4259-46a5-b05e-7a1efa9c90bd.png)
When I enter the page I cannot see the icons and nothing</div>

**Comment by WillypaDJ** [comment]
yes

**Comment by corei8** [comment]
It is happening to me as well.

**Comment by corei8** [comment]
I just checked on Safari, MacOS. The site is working as it ought. It does not work with Brave on MacOS for me. I get what the screenshot above displays.

**Comment by WillypaDJ** [comment]
thanks. I will use safari for this.

**Comment by liyz15** [comment]
Also happening in Edge. Safari works fine.

**Comment by liyz15** [comment]
![image](https://user-images.githubusercontent.com/32741741/145582176-e2c106ab-188a-4b81-af43-49eadbbe861e.png)

Though I'm not familiar with websites, it looks like some session/token issues. So I deleted all the cookies and it works now! 🎉

**Comment by elrumo** [comment]
Glad to hear that it's working now! I'll see if I can do something to fix that so it doesn't happen in the future

**Comment by elrumo** [comment]
Had you logged in by any chance?

**Comment by liyz15** [comment]
No I hadn't logged in. Not sure if it's relevant but I visited the website months ago. Thanks a lot for your fabulous work!
