### ISSUE TITLE
League of Legends 

### ISSUE THREAD

**Issue by ineffablecharles** [elrumo/macOS_Big_Sur_icons_replacements#134]
Hello man, I just installed Big Sur, it's beautiful, but the icons that you and your comrades did, they complete the system!
If you could do a League of Legends icns, it would be awesome
Thanks!

**Comment by jsdu** [comment]
Would like this as well!

**Comment by elrumo** [comment]
Thanks! @Aljarus has done the League Of Legends icons :)
