### ISSUE TITLE
Broken icon link 

### ISSUE THREAD

**Issue by shinra-electric** [elrumo/macOS_Big_Sur_icons_replacements#1486]
I've come across at least one icon that has a broken link (this [Portal](https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/b2f336dc08b1a8b704faccf4d7b5bc09_tIdy1BXfhN.icns) one here).

Clicking on the link leads to a "Access denied" XML file: 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>VN0VDSQN632WTQ2G</RequestId>
<HostId>
TuUNGoP2pG1xxLaACqYh1XgoQ8l8sGS1pKA6yaGp8OqEo6coP/EbsvPUB2Pi2vzwGewUlQ0nHosKjr/jA/fV7jDO7zBOVyywXJc5aiA8lfI=
</HostId>
</Error>
```

**Comment by shinra-electric** [comment]
I found another broken link [here](https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/ae136945718671fffd7989eb3ac276ee_RPCS3-Arm.icns)

**Comment by elrumo** [comment]
@shinra-electric  See this issue: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/1506
