### ISSUE TITLE
Neon Chrome Icon XML No Style Error

### ISSUE THREAD

**Issue by beck1888** [elrumo/macOS_Big_Sur_icons_replacements#1488]
The link for a Chrome icon is broken. The site displays this error:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>95TF6XTS7FB9EKBY</RequestId>
<HostId>Vivhb/dp6KbkX+bkYTf5P3rHFs+SyHiuK0MU3fo+NtVNcVrCO1fD266b37rGuqvSGReXWbOvcBk=</HostId>
</Error>
```

This is the offending link: https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/1866d47c5c488b18cb9fb5bf582076a4_bxdhzHp8B9.icns

This is the icon:
<img width="224" alt="image" src="https://github.com/elrumo/macOS_Big_Sur_icons_replacements/assets/123674650/3facb60d-a799-4b20-8bcd-1bfc2dd885b3">

**Comment by elrumo** [comment]
See this issue: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/1506
