### ISSUE TITLE
Broken link for icon

### ISSUE THREAD

**Issue by pininozs** [elrumo/macOS_Big_Sur_icons_replacements#1489]
An icon I uploaded a while back has a broken download link. It's had it since it's been uploaded.
Can you fix it?

It's the uTorrent icon found [here](https://macosicons.com/#/u/manuzavala)

Also, I noticed someone else reported the same issue with another icon on the "Discussions" section, this is their [post](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/discussions/1485).

Thank you.

**Comment by pininozs** [comment]
[This](https://macosicons.com/#/u/julesiscool) Ryujinx icon is broken too

**Comment by 0PandaDEV** [comment]
For me all icons are broken I get a AccessDenided from the back4app.com backend.

**Comment by thebentiq** [comment]
[Link](https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/b60a964e4dd9c35c5d959b4f3e34d1b5_Plasticity.icns) to the Plasticity icon also does not work, sadly

**Comment by elrumo** [comment]
@0PandaDEV are all the icon links still broken for you? I can't seem to be able to replicate the issue.

https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/1493#issuecomment-2381448844
