### ISSUE TITLE
FB Messenger?

### ISSUE THREAD

**Issue by cluegithub** [elrumo/macOS_Big_Sur_icons_replacements#16]
Facebook Messenger icon (like the Big Sur Messages icon with less weird shadows)?

**Comment by RobSjaras** [comment]
+1 for this!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/FB_messenger.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/FB_messenger.icns)<br>[ Facebook Messenger ](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/FB_messenger.icns)

Something like this?
