### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by austincondiff** [elrumo/macOS_Big_Sur_icons_replacements#171]
# Name of app
Paste

# Website of the app requested
https://pasteapp.io/

| Original | Proposed |
|:-------------------------:|:-------------------------:|
|<img width="256" alt="original-paste-icon" src="https://user-images.githubusercontent.com/806104/89702263-1b0b2300-d905-11ea-9611-f0f7dfa83292.png"> |  <img width="256" alt="big-sur-paste-icon" src="https://user-images.githubusercontent.com/806104/89702249-f616b000-d904-11ea-82c3-074db7f1b011.png"> |

ICNS Download: [paste.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5044626/paste.icns.zip)

**Comment by elrumo** [comment]
Done, it's on the repo.
