### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by austincondiff** [elrumo/macOS_Big_Sur_icons_replacements#173]
# Name of app
Postman

# Website of the app requested
https://www.postman.com/

| Original | Proposed |
|:-------------------------:|:-------------------------:|
|<img width="256" alt="original-postman-icon" src="https://user-images.githubusercontent.com/806104/89702233-b18b1480-d904-11ea-88e5-962f9689be08.png"> |  <img width="256" alt="big-sur-postman-icon" src="https://user-images.githubusercontent.com/806104/89702221-7d175880-d904-11ea-87f1-109d3c3a6cdb.png"> |

ICNS Download: [postman.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5044623/postman.icns.zip)

**Comment by elrumo** [comment]
Done :)
