### ISSUE TITLE
IntelliJ IDEA

### ISSUE THREAD

**Issue by austincondiff** [elrumo/macOS_Big_Sur_icons_replacements#175]
# Name of app
IntelliJ IDEA

# Website of the app requested
https://www.jetbrains.com/idea/

| Original | Proposed |
|:-------------------------:|:-------------------------:|
|<img width="256" alt="original-intellij-icon" src="https://user-images.githubusercontent.com/806104/89694116-3f9bd680-d8d6-11ea-923c-1282e6852670.png"> |  <img width="256" alt="big-sur-intellij-icon" src="https://user-images.githubusercontent.com/806104/89694037-006d8580-d8d6-11ea-898e-dc46222d1adf.png"> |

ICNS Download: [intellij.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5044126/intellij.icns.zip)

**Comment by elrumo** [comment]
Done
