### ISSUE TITLE
Table Plus

### ISSUE THREAD

**Issue by austincondiff** [elrumo/macOS_Big_Sur_icons_replacements#176]
# Name of app
Table Plus

# Website of the app requested
https://tableplus.com/

| Original | Proposed |
|:-------------------------:|:-------------------------:|
|<img width="256" alt="original-table-plus-icon" src="https://user-images.githubusercontent.com/806104/89695024-34e24100-d8d8-11ea-9d89-8a4f190164d7.png"> |  <img width="256" alt="lbig-sur-table-plus-icon" src="https://user-images.githubusercontent.com/806104/89695066-59d6b400-d8d8-11ea-99a0-365d3dc36630.png"> |

ICNS Download: [table-plus.icns.zip](https://github.com/TablePlus/TablePlus/files/5044156/table-plus.icns.zip)

Also requested on their repo at https://github.com/TablePlus/TablePlus/issues/2025.

**Comment by elrumo** [comment]
Done, it's up on the repo
