### ISSUE TITLE
Blender

### ISSUE THREAD

**Issue by andresfelive** [elrumo/macOS_Big_Sur_icons_replacements#18]

**Comment by andresfelive** [comment]
My attempt on blender, light and dark. Zip with the .icns files

![blenderb](https://user-images.githubusercontent.com/63774784/89115704-f7516400-d450-11ea-9c50-e581bb7b5ce2.png)
![blender](https://user-images.githubusercontent.com/63774784/89115706-f91b2780-d450-11ea-9411-a53700e07610.png)

[Blender.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5011658/Blender.zip)

**Comment by elrumo** [comment]
Looks awesome! You've done a fantastic job 👍 

Adding it to the repo.
