### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by austincondiff** [elrumo/macOS_Big_Sur_icons_replacements#193]
# Name of app
Nova

# Website of the app requested
https://panic.com/nova/

| Original | Proposed |
|:-------------------------:|:-------------------------:|
|<img width="256" alt="original-nova-icon" src="https://user-images.githubusercontent.com/806104/89702791-78ee3980-d90a-11ea-88d0-e3fbc516d183.png"> |  <img width="256" alt="big-sur-nova-icon" src="https://user-images.githubusercontent.com/806104/89702803-a89d4180-d90a-11ea-9b05-6428f776b641.png"> |

ICNS Download: [nova.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5044681/nova.icns.zip)

**Comment by elrumo** [comment]
Looks great! Just uploaded it to the repo.
