### ISSUE TITLE
Look like the Instagram icon copy from my design

### ISSUE THREAD

**Issue by csee** [elrumo/macOS_Big_Sur_icons_replacements#201]
### Look like the Instagram icon copy from my design: https://dribbble.com/shots/12254763-Instagram-Logo#comment-9759440

**Comment by elrumo** [comment]
Hi, it does! I did not make the icon and I didn't know that had happened, sorry about that. If you'd like to keep the icon on this repo I'll add you to the credits, but if you prefer I can remove it completely.

**Comment by Ovennell** [comment]
@csee Hi, I found it on Reddit, I forgot to put the credit, I hope I don't cause inconvenience.

**Comment by csee** [comment]
Ok,keep it. Is fine:)
