### ISSUE TITLE
Icons8

### ISSUE THREAD

**Issue by andresfelive** [elrumo/macOS_Big_Sur_icons_replacements#21]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Icons_8.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Icons_8.icns)<br>[Icons8](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Icons_8.icns)

Done
