### ISSUE TITLE
Spark Mail

### ISSUE THREAD

**Issue by thedb11** [elrumo/macOS_Big_Sur_icons_replacements#211]
Spark Mail

https://sparkmailapp.com/

**Comment by elrumo** [comment]
This one is already on the repo, it's actually one of the first ones I made as it's also one of the apps I use the most. 😄 
https://macosicons.com

**Comment by thedb11** [comment]
Yeah, I just found it a few days ago after. Love the icons!!

Thanks,
Dylan Baer
dylanbaer.com
