### ISSUE TITLE
Macs Fan Control

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#218]
Macs Fan Control

**High Resolution Image:**
<img width="512" alt="Macs Fan Control" src="https://user-images.githubusercontent.com/69454424/89765447-07c3a780-daff-11ea-9083-675cc90efe79.png">

I was unable to upload the .icns file to this post because GitHub doesn't allow me, Im sure you can convert the .png to .icns yourself fairly quickly.

Enjoy the icon.

**Comment by elrumo** [comment]
Looks great! Just uploaded it. For next time, if GitHub won't allow you to upload the other icons a solution could be using a shared folder on Google Drive, OneDrive, Dropbox or something like that.
