### ISSUE TITLE
uTorrent

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#219]
uTorrent

**High Resolution Image:**
<img width="512" alt="Utorrent" src="https://user-images.githubusercontent.com/69454424/89765367-d8149f80-dafe-11ea-9964-b435d2c01319.png">

I was unable to upload the .icns file to this issue because GitHub doesn't allow me, Im sure you can convert the .png to .icns yourself fairly quickly.

Enjoy the icon.

**Comment by elrumo** [comment]
Done.
