### ISSUE TITLE
Skype icon

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#221]
Skype

High Resolution Image:
<img width="512" alt="Skype2" src="https://user-images.githubusercontent.com/69454424/89765271-ad2a4b80-dafe-11ea-8927-5aa6ce74dfc7.png">

I was unable to upload the .icns file to this post because GitHub doesn't allow me, Im sure you can convert the .png to .icns yourself fairly quickly.

Enjoy the icon.

**Comment by elrumo** [comment]
Done.
