### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#227]
Steam

Noticed Steam icon wasn't there so I made one. 
**Heres the icon:**

<img width="512" alt="Steam" src="https://user-images.githubusercontent.com/69454424/89831317-4fc9e500-db66-11ea-8db8-b473a966bdd6.png">

**Comment by elrumo** [comment]
Steam is already on the pack, but I'll add it anyway as an alternative version
