### ISSUE TITLE
PhpStorm

### ISSUE THREAD

**Issue by Squirrelf** [elrumo/macOS_Big_Sur_icons_replacements#233]
### [phpstorm.zip with icns and pngs](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5054607/phpstorm.zip)

I made this for fun, not going to do the rest fo the jetbrain suite of apps. But thought I would share this one anyway. 
Can more than likely be improved, but good enough as an initial concept.
<img width="512" alt="phpstorm" src="https://user-images.githubusercontent.com/30702722/89855255-4420f300-db53-11ea-87fa-6cf33ae96ba6.png">

**Comment by elrumo** [comment]
Looks great! Just added it to the repo

**Comment by elrumo** [comment]
Looks great! Just added it to the repo

**Comment by yashrajchhabra** [comment]
@Squirrelf 
Can you share the original design files for this icon. I want create similar icons for pycharm and webstorm.

Thanks

**Comment by Squirrelf** [comment]
> @Squirrelf
> Can you share the original design files for this icon. I want create similar icons for pycharm and webstorm.
> 
> Thanks

Happy to, I’ll post it as soon as I get home.
I made it with Affinity Designer just to see how well the app translates from illustrator ( since I’m trying to see if I can get away from Adobe subscription )
I don’t have sketch so I didn’t use that.

If you don’t have affinity designer you can get a trial to make those other icons or export the file from it to get it into another program like illustrator or sketch.

**Comment by elrumo** [comment]
If you don't mind, I'll also add them to the repo as templates. We currently have one for Sketch and Photoshop so it could be useful for others too. The templates currently are on the Design root folder [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/tree/master/design)

> > @Squirrelf
> 
> > Can you share the original design files for this icon. I want create similar icons for pycharm and webstorm.
> 
> > 
> 
> > Thanks
> 
> 
> 
> Happy to, I’ll post it as soon as I get home.
> 
> I made it with Affinity Designer ( macOS ) just to see how well the app translates from illustrator ( since I’m trying to see if I can get away from Adobe subscription )
> 
> I don’t have sketch so I didn’t use that.
> 
> 
> 
> If you don’t have affinity designer you can get a trial ( it’s also available on windows I think ) to make those other icons or export the file from it to get it into another program like illustrator or sketch.
> 
>

**Comment by Squirrelf** [comment]
> If you don't mind, I'll also add them to the repo as templates. We currently have one for Sketch and Photoshop so it could be useful for others too. The templates currently are on the Design root folder [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/tree/master/design)
> 
> > > @Squirrelf
> > 
> > 
> > > Can you share the original design files for this icon. I want create similar icons for pycharm and webstorm.
> > 
> > 
> > > 
> > 
> > 
> > > Thanks
> > 
> > 
> > Happy to, I’ll post it as soon as I get home.
> > I made it with Affinity Designer ( macOS ) just to see how well the app translates from illustrator ( since I’m trying to see if I can get away from Adobe subscription )
> > I don’t have sketch so I didn’t use that.
> > If you don’t have affinity designer you can get a trial ( it’s also available on windows I think ) to make those other icons or export the file from it to get it into another program like illustrator or sketch.

I don't mind at, all I'll clean up the file a bit and post it here so you can add it

**Comment by Squirrelf** [comment]
@yashrajchhabra the template has the PHPstorm icon as hidden layer, so just hide the "Starting_template" Layer, and unhide the PHPHSTORM_Example layer

@elrumo this file as ready as is, I left a couple reference icons I used as hidden layer
and kept the PHPstorm icon as an example in a hidden layer
the file has a lot of alignment guides, which I left since they can be useful.

the template is the basic vectorial shape, that basic yellow icon, with a couple effects, shadow and a small bevel (same settings I used for the phpstorm icon)


[bigsur_template.afdesign.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5092673/bigsur_template.afdesign.zip)

<img width="512" alt="bigsur_template" src="https://user-images.githubusercontent.com/30702722/90562945-4b9e5880-e160-11ea-826c-058d0474bb1c.png">
