### ISSUE TITLE
 Quick Time, Docker, TurboBoostSwitcher, LeagueOfLegends,Honey, Grammarly & PopcornTime

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#235]
QuickTime:
<img width="512" alt="quick time Icon" src="https://user-images.githubusercontent.com/69454424/89860521-50856a00-dbac-11ea-98a0-fb00af79cd4e.png">

Docker:
<img width="512" alt="Docker icon" src="https://user-images.githubusercontent.com/69454424/89860947-592a7000-dbad-11ea-85d8-806c0212b35c.png">

Turbo Boost Switcher:
<img width="512" alt="Turbo Boost Switcher Pro" src="https://user-images.githubusercontent.com/69454424/89861089-a0186580-dbad-11ea-8889-72e5318f51d2.png">

League Of Legends:
<img width="512" alt="League" src="https://user-images.githubusercontent.com/69454424/89860857-208a9680-dbad-11ea-8e80-daf704ef8e86.png">

Honey:
<img width="512" alt="Honey" src="https://user-images.githubusercontent.com/69454424/89860561-67c45780-dbac-11ea-88da-c352c0e63061.png">

Grammarly:
<img width="512" alt="grammarly" src="https://user-images.githubusercontent.com/69454424/89860820-05b82200-dbad-11ea-9691-229122467c03.png">

Popcorn Time:
<img width="512" alt="Popcorn" src="https://user-images.githubusercontent.com/69454424/89861004-78290200-dbad-11ea-9182-c709a82ccc88.png">

Enjoy friend :)

**Comment by elrumo** [comment]
Just uploaded them, although I left out Quicktime as it's already bundled with Big Sur and already has the new icon.

**Comment by Aljarus** [comment]
Dont you think the new quicktime icon looks disappointing?
