### ISSUE TITLE
To Submit: Reality Composer

### ISSUE THREAD

**Issue by ProgrammerGeek123** [elrumo/macOS_Big_Sur_icons_replacements#242]
### Name of app
Reality Composer
### Link to download the icons
To remember to submit:
- A low res .png
- A high res .png
- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar

low res png: 
<img width="75" alt="Screen Shot 2020-08-11 at 12 23 50 PM" src="https://user-images.githubusercontent.com/69526506/89922855-a28ab780-dbcd-11ea-8049-f1a9fa3a68f3.png">
high res png: 
<img width="554" alt="Screen Shot 2020-08-11 at 12 23 12 PM" src="https://user-images.githubusercontent.com/69526506/89922872-a9b1c580-dbcd-11ea-8129-599098b44736.png">
icns: (zip) 
[RealityComposer.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5058134/RealityComposer.zip)

**Comment by elrumo** [comment]
Isn't that already the icon Apple ships with Reality composer?

**Comment by ProgrammerGeek123** [comment]
Yes. There was a request for it so I posted it.

**Comment by elrumo** [comment]
Fair enough, I'll upload it here any way.
