### ISSUE TITLE
Icon not changing in Bug Sur

### ISSUE THREAD

**Issue by vebaev** [elrumo/macOS_Big_Sur_icons_replacements#250]
I tried to change the Spotify icon (from the Get info), but instead the icon changed to a Preview app icon  (Big Sur Public 11.0 Beta (20A5343j)?

**Comment by elrumo** [comment]
Did you download the right .icns file? Where did you download it from? What you described usually happens when using a .png image instead. Try this [link](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Spotify_Alternate.icns), and if does't work let me know.

**Comment by vebaev** [comment]
I tried with the file you provided and the result is the same.

**Comment by joepool** [comment]
I had this issue, rebooting with the application installed and icon downloaded solved it for me.

**Comment by vebaev** [comment]
Yes rebooting solve the issue :)

**Comment by gottabeleGIT** [comment]
You can also fix this by running this terminal command `killall Dock`
No reboot required

**Comment by Mr1262** [comment]
Good 
Thanks 😊

**Comment by angristan** [comment]
(and then you have to launch/relaunch the apps if they are in your Dock)

**Comment by elrumo** [comment]
An even easier way to fix it is to simply click on the app icon on the dock while you press CMD

**Comment by angristan** [comment]
Even better! Thanks
