### ISSUE TITLE
feature request: Installer support

### ISSUE THREAD

**Issue by neet** [elrumo/macOS_Big_Sur_icons_replacements#253]
Hi, thank you for making an awesome project, I really love the consistency of the icons rounded!

Currently, for setting the icon you have to open "Get Info" and set the `icns` file manually which was painful for me, so I created a [CLI tool](https://github.com/neet/big-sur-icons-replacer) that replaces/resets all icons inside the `/Applications` folder using Node.js. Although it still has minor problems (such as cannot choose alt version, Adobe won't be replaced since it's nested in another folder, apps that don't have the exact same filename as icon won't be replaced), it works fine basically.

Likewise, do you have any plans to support an installer like that? If it's needed, I'd like to brush-up the existing one and create Pull Request for this!

**Comment by austincondiff** [comment]
I like this idea! Maybe wrap it in an electron menubar app. Whenever an app is updated sometimes my applied icon is reset to the original app icon, so then I need to go and replace it again. This is a headache and if this script could also detect this and automatically replace the icon again after an update that would be awesome. 

I'd like to see some UI that shows detected apps for replace, and available icon options for each detected app. Maybe the user does not want to replace some icons so I could see some check/uncheck behavior.

I would be happy to help with this project!

**Comment by elrumo** [comment]
> I like this idea! Maybe wrap it in an electron menubar app. Whenever an app is updated sometimes my applied icon is reset to the original app icon, so then I need to go and replace it again. This is a headache and if this script could also detect this and automatically replace the icon again after an update that would be awesome. 
> 
> 
> 
> I'd like to see some UI that shows detected apps for replace, and available icon options for each detected app. Maybe the user does not want to replace some icons so I could see some check/uncheck behavior.
> 
> 
> 
> I would be happy to help with this project! To use your CLI tool we would use this approach... https://manu.ninja/simple-electron-gui-wrapper-for-a-command-line-utility/

I thought exactly the same as I was reading the issue above. If @neet or anyone else has already built a rudimentary backend, we could design and build the front end and wrap it as an electron app. I'd also be more than happy to work on the front end. 
I'll have a look with the script @neet wrote when I get back home this evening.

**Comment by neet** [comment]
Electron would definitely be better than CLI if we could! Also, I totally agree with the "reset on update" issue mentioned by @austincondiff.

I used a third-party library [fileicon](https://github.com/mklement0/fileicon) to call macOS API in the CLI I shared above because I'm not familiar with the macOS at all. Other than set and remove, it also has features to check if an icon has already set, or get the current icon. However, I have no idea how to listen to "post-update" event on macOS 🤔

**Comment by austincondiff** [comment]
@neet you would simply put a watcher on that application file. If it is replaced (deleted and put back) we would reapply the new icon.

**Comment by Mr1262** [comment]
👍

**Comment by zebHub** [comment]
Someone already has a neat project doing this pretty much https://github.com/rikumi/iconsur
