### ISSUE TITLE
Instructions not clear

### ISSUE THREAD

**Issue by AbduAref** [elrumo/macOS_Big_Sur_icons_replacements#254]
I dont seem to be able to find a way to change these icons on windows

**Comment by elrumo** [comment]
The icon format used here, which is .icns, is specifically used by Apple on macOS. Windows uses a different file format, but I'm sure it could easily be changed using the high def .pngs from [here](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/tree/master/icons/png/high-res)

**Comment by AbduAref** [comment]
I have tried that but they just turn out to be really small when they are replaced
