### ISSUE TITLE
Bitwarden

### ISSUE THREAD

**Issue by vlourme** [elrumo/macOS_Big_Sur_icons_replacements#256]
### Name of app
Bitwarden

### Website of the app requested
https://bitwarden.com

Thank you!

**Comment by vlourme** [comment]
This is already defined in the README.

**Comment by gottabeleGIT** [comment]
The issue would still help track the progress of the icon, so I don't think it would be required to close or not file an issue even if the application is already in the README

**Comment by Mr1262** [comment]
https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/256#issue-677768793

**Comment by gottabeleGIT** [comment]
Nevermind: #296 :p
