### ISSUE TITLE
Pycharm by Jetbrains

### ISSUE THREAD

**Issue by pigeonmoney** [elrumo/macOS_Big_Sur_icons_replacements#258]
### Name of app
Pycharm
### Website of the app requested
https://www.jetbrains.com/pycharm/

**Comment by Mr1262** [comment]
Thanks 🙏

**Comment by Mr1262** [comment]
Name of app:  bybit

https://www.bybit.com/en-US/?source=google&medium=cpc&campaign=brand&content=evergreen&gclid=EAIaIQobChMIlcn8u7iW6wIVSRV7Ch2vfQzFEAAYASAAEgIp_fD_BwE
