### ISSUE TITLE
AnyTrans Logo

### ISSUE THREAD

**Issue by MaxxBzt** [elrumo/macOS_Big_Sur_icons_replacements#263]
Here my first try with AnyTrans logo, I don't know if anyone use it but it's useful and I wanted to try it. 
[AnyTrans.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5065324/AnyTrans.zip)

**Comment by Mr1262** [comment]
https://github.com/elrumo/macOS_Big_Sur_icons_replacements/pull/264
