### ISSUE TITLE
HuionTablet, qBittorrent, Intel Power Gadget

### ISSUE THREAD

**Issue by rishabh-design** [elrumo/macOS_Big_Sur_icons_replacements#293]
### Link to download the icons
HuionTablet: https://1drv.ms/u/s!AkiwK0w-puiFg5AtFDojfZpnUAVx_Q?e=ety2BN
qBittorrent: https://1drv.ms/u/s!AkiwK0w-puiFg5AwbUidfSZzRLtj9A?e=MWb8cY
Intel Power Gadget: https://1drv.ms/u/s!AkiwK0w-puiFg5AzX0rGQ3J_f122oQ?e=Ear5aT

**Comment by Mr1262** [comment]
👍

**Comment by elrumo** [comment]
Done
