### ISSUE TITLE
Microsoft Office icons are bigger than the rest

### ISSUE THREAD

**Issue by rishabh-design** [elrumo/macOS_Big_Sur_icons_replacements#294]
Word, powerpoint, excel and onenote (possibly outlook too) are larger than the rest of the icons.

**Comment by elrumo** [comment]
I think it's just an optical illusion because of the element that's sticking out . Have a look at this screen recording I made comparing icon sizes. 
![macOS icons](https://user-images.githubusercontent.com/36299870/90296275-52407d80-de8b-11ea-9c98-f46d871693f6.gif)

**Comment by rishabh-design** [comment]
You are right, my eyes played tricks on me. I could swear the icon looks way bigger than it actually is. My apologies.

<img width="448" alt="Screenshot 2020-08-15 at 4 36 27 AM" src="https://user-images.githubusercontent.com/69663176/90298813-36e86900-deb1-11ea-8345-7d005f9ed54e.png">

**Comment by elrumo** [comment]
Hahah no problem, I think it's funny how not having a white border makes the icon look bigger. The beauty of design :)
