### ISSUE TITLE
Filezilla

### ISSUE THREAD

**Issue by diegograziano** [elrumo/macOS_Big_Sur_icons_replacements#30]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Filezila.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Filezila.icns)<br>[Filezila](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Filezila.icns)

Done
