### ISSUE TITLE
OmniFocus

### ISSUE THREAD

**Issue by owenfiscus** [elrumo/macOS_Big_Sur_icons_replacements#31]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/OmniFocus.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/OmniFocus.icns)<br>[OmniFocus](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/OmniFocus.icns)

Done

**Comment by owenfiscus** [comment]
Wow that's beautiful. Thank you.
