### ISSUE TITLE
Reeder

### ISSUE THREAD

**Issue by rezzo** [elrumo/macOS_Big_Sur_icons_replacements#33]
Hi,
I would love to see you redo the Reeder icon. thx
https://reederapp.com/

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Reeder.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Reeder.icns)<br>[Reeder](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Reeder.icns)

Done
