### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by rezzo** [elrumo/macOS_Big_Sur_icons_replacements#34]
Hi,
I would love to see you redo the Discord icon. thx
https://discord.com/new/download

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Discord.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Discord.icns)<br>[Discord](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Discord.icns)

Here you go :)
