### ISSUE TITLE
To Submit: SurfShark, TickTick, Bear (gray), & Firefox nightly.

### ISSUE THREAD

**Issue by josevazquz** [elrumo/macOS_Big_Sur_icons_replacements#365]
### SurfShark, TickTick, Bear (gray), & Firefox nightly. ``
![big sur](https://user-images.githubusercontent.com/67874369/90844081-16953000-e331-11ea-8e85-54170966927e.jpg)

### folder: https://drive.google.com/file/d/14MDpEgSCeBVznzSC5ypUC0LMYVf9QFdq/view?usp=sharing

**Comment by elrumo** [comment]
Just added them :)
