### ISSUE TITLE
Pages, Numbers, and Keynote

### ISSUE THREAD

**Issue by ProgrammerGeek123** [elrumo/macOS_Big_Sur_icons_replacements#368]
### Name of app
Pages, Numbers,  and Keynote
### Zip:
[Archive.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5109657/Archive.zip)

Note: credit to Stijn de Vries: https://stijndv.com/goodies/

**Comment by ProgrammerGeek123** [comment]
No. I found them from several sources online. I believe I credited them, and they are also the official Apple Icons.

**Comment by elrumo** [comment]
I'm sure they wouldn't have an issue, but I think we should first ask them for permission. They might not want to have them here, so just in case.

**Comment by elrumo** [comment]
I've just sent him a message on Twitter, I'll upload them if he responds

**Comment by ProgrammerGeek123** [comment]
You can upload them and just say "credit to Stijn de Vries" under the app icon on the web and maybe even put a link.

**Comment by elrumo** [comment]
Done
