### ISSUE TITLE
To Submit: InstallMacOS home-made icon

### ISSUE THREAD

**Issue by ProgrammerGeek123** [elrumo/macOS_Big_Sur_icons_replacements#371]
### Name of app: Install macOS (BigSur)
has 4 icons for each type of Mac.
### Zip:
[icons.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5110313/icons.zip)

**Comment by elrumo** [comment]
Could you please also upload a low res png (256x256) and a high res png too (1024x1024) to inside the .zip file please?

**Comment by ProgrammerGeek123** [comment]
ok.
[install.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5120545/install.zip)

**Comment by ProgrammerGeek123** [comment]
Hi, I made a pull request instead.
