### ISSUE TITLE
Pixelmator Pro

### ISSUE THREAD

**Issue by rezzo** [elrumo/macOS_Big_Sur_icons_replacements#38]
Hi,
I would love to see you redo the Pixelmator Pro icon. thx
https://apps.apple.com/us/app/pixelmator-pro/id1289583905

**Comment by elrumo** [comment]
Done, I'll commit the icon tomorrow morning

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Pixelmator_Pro.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Pixelmator_Pro.icns)<br>[Pixelmator Pro](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Pixelmator_Pro.icns)

Here's the icon, I'll do the standard Pixelmator soon too.
