### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by timswagwalker** [elrumo/macOS_Big_Sur_icons_replacements#39]
I'd love an [Atom](atom.io) icon!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Atom.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Atom.icns)<br>[Atom](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Atom.icns)

Done
