### ISSUE TITLE
Malwarebytes

### ISSUE THREAD

**Issue by Mashoe** [elrumo/macOS_Big_Sur_icons_replacements#4]
Inspiration: https://apps.apple.com/us/app/malwarebytes-mobile-security/id1327105431

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Malwarebytes.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Malwarebytes.icns)<br>[Malwarebytes](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Malwarebytes.icns)

Here it is :)
