### ISSUE TITLE
HandBrake

### ISSUE THREAD

**Issue by joeisastaple** [elrumo/macOS_Big_Sur_icons_replacements#41]
Everyone's fav video codec tool!

**Comment by bennetfabian** [comment]
It definitely is, so it has it's own Big Sur style icon now. Issue can as well be closed. @elrumo :)

**Comment by bradleysepos** [comment]
Hate to be a Debbie Downer, but please respect upstream projects' licenses. https://github.com/HandBrake/HandBrake/issues/3053#issuecomment-668196726

**Comment by gottabeleGIT** [comment]
> The HandBrake icon/logo is licensed [CC BY-SA 4.0](https://github.com/HandBrake/HandBrake/blob/ac616df17d3d5f2482ab1263f0560ee8e1a253ea/graphics/CC_BY-SA_4.0_INT). As such, this derivative design cannot be relicensed GPL 3.0, so it's technically a license violation.

**Comment by gottabeleGIT** [comment]
https://github.com/HandBrake/HandBrake/issues/3053#issuecomment-674437853
