### ISSUE TITLE
To submit: Desktop Goose

### ISSUE THREAD

**Issue by LudoLud** [elrumo/macOS_Big_Sur_icons_replacements#410]
Desktop Goose

PNG (low): https://ig-89.webselfsite.net/file/si1659991/Goose_Desktop_Low-fi25370563x190.png
PNG (high): https://ig-89.webselfsite.net/file/si1659991/Goose_Desktop_High-fi25370560x190.png
ICNS: https://ig-89.webselfsite.net/file/si1659991/download/Desktop_Goose-fi25370538.icns

**Comment by elrumo** [comment]
Just uploaded it. :)
