### ISSUE TITLE
iMovie

### ISSUE THREAD

**Issue by AstralBirthVoid1** [elrumo/macOS_Big_Sur_icons_replacements#42]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/iMovie.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/iMovie.icns)<br>[iMovie](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/iMovie.icns)

Here it is, but I think is just a matter of time before Apple updates it. Enjoy it in the meantime :)

**Comment by AstralBirthVoid1** [comment]
Thank you so much!
