### ISSUE TITLE
AI template uses the wrong form for the icon

### ISSUE THREAD

**Issue by holvanato** [elrumo/macOS_Big_Sur_icons_replacements#425]
In https://github.com/elrumo/macOS_Big_Sur_icons_replacements/blob/master/design/Template%20-%20Icon%20-%20App.ai the icon form (rectangle with simple round corners) used does not match the one in Apple's Human Interface Guidelines and the downloadable resources for macOS 11 (with curvature continuity) at https://developer.apple.com/design/resources/ . Also, the size should be 824px in a 1024px area.

See comment on the commit: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/commit/79b97e2014a1582e37f0262fbfeabc593c0f0e06#commitcomment-42040072

**Comment by elrumo** [comment]
I've fixed the issue.
