### ISSUE TITLE
VECTORNATOR PRO

### ISSUE THREAD

**Issue by WeLeBro** [elrumo/macOS_Big_Sur_icons_replacements#428]
### Name of app
Vectornator Pro
### Website of the app requested
https://www.vectornator.io/

**Comment by elrumo** [comment]
The icon has just been added.

**Comment by Coccobrutto** [comment]
Hello, I’m tring to solve a problem with my Vectornator start to crush today and I find only this place. The question is if I remove the app to reinstal later I will lose all the files? If you know a right place where I can ask to fix it I appreciate
Thankyou 
Stefano
