### ISSUE TITLE
To Submit: Quicken

### ISSUE THREAD

**Issue by elij4110** [elrumo/macOS_Big_Sur_icons_replacements#433]
### Link to download the icons
To remember to submit:
- A low res .png
- A high res .png

[Quicken.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5178573/Quicken.icns.zip)
![Template - Icon - App-02](https://user-images.githubusercontent.com/69415129/92313006-14b3a980-ef8c-11ea-8ca2-0a1ecdf92f31.png)

**Comment by elrumo** [comment]
Done
