### ISSUE TITLE
To Submit: Sketchup Layout

### ISSUE THREAD

**Issue by elij4110** [elrumo/macOS_Big_Sur_icons_replacements#434]
### Link to download the icons
To remember to submit:
- A low res .png
- 
![Sketchup-Layout-02](https://user-images.githubusercontent.com/69415129/92313016-37de5900-ef8c-11ea-9260-1d0b500d88cb.png)

[Sketchup-Layout.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5178576/Sketchup-Layout.icns.zip)

**Comment by elrumo** [comment]
Done
