### ISSUE TITLE
To Submit: Sketchup Style Builder

### ISSUE THREAD

**Issue by elij4110** [elrumo/macOS_Big_Sur_icons_replacements#435]
### Link to download the icons
To remember to submit:
- A low res .png

[Sketchup-Style-Builder.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5178577/Sketchup-Style-Builder.icns.zip)
![Template - Icon - App2-02](https://user-images.githubusercontent.com/69415129/92313040-68be8e00-ef8c-11ea-9275-03c1f8b48d17.png)

**Comment by elrumo** [comment]
Looks great! Just so I can add them to the site, would you mid uploading a low res (256px) and high res png of the icon?

**Comment by elij4110** [comment]
![stylebuilder](https://user-images.githubusercontent.com/69415129/92313726-7aa42f00-ef94-11ea-8993-cc6b0cd68520.png)

I do not have a low res and high res, but here is the png file that I used.

**Comment by elrumo** [comment]
Done, just uploaded them. Thanks!
