### ISSUE TITLE
iStudiez

### ISSUE THREAD

**Issue by topazbarziv** [elrumo/macOS_Big_Sur_icons_replacements#437]
### Name of app
iStudiez
### Website of the app requested
https://istudentpro.com

Original logo for macOS:
![alt text](https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/5c/d7/8d/5cd78d3a-6512-70d6-141f-7833ceef7104/AppIconFlat-0-85-220-0-0-0-0-4-0-0-0-2x-sRGB-0-0-0.png/246x0w.png "Logo Title Text 1")

**Comment by rakleed** [comment]
@topazbarziv There is currently no icon for this app: https://macosicons.com/iStudiez%20Pro

**Comment by topazbarziv** [comment]
@rakleed True, but in the program [https://replacicon.app](https://replacicon.app) it appears:
![image](https://user-images.githubusercontent.com/18365476/119197740-ea116e80-ba90-11eb-99db-a4654bb8ea10.png)
