### ISSUE TITLE
Mate Translate

### ISSUE THREAD

**Issue by andresfelive** [elrumo/macOS_Big_Sur_icons_replacements#438]
### Link to download the icons

- Low res
![Low res](https://user-images.githubusercontent.com/63774784/92325783-d0b7b780-f012-11ea-97f6-0f4432cc4369.png)

- High res
![high res](https://user-images.githubusercontent.com/63774784/92325789-dad9b600-f012-11ea-994a-b13c6a71a336.png)

- Icns
[Mate Translate.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5179632/Mate.Translate.zip)

**Comment by elrumo** [comment]
Done
