### ISSUE TITLE
To Submit: [Mos]

### ISSUE THREAD

**Issue by applekillerbyjames** [elrumo/macOS_Big_Sur_icons_replacements#442]
### Name of app
Mos
### Link to download the icons
![Mos](https://user-images.githubusercontent.com/43358890/92334558-0b861380-f044-11ea-9193-2d32bcc548a3.png)

To remember to submit:
- A low res .png
- A high res .png
- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar

**Comment by elrumo** [comment]
Thanks for the icon! I just added it to the repo.
