### ISSUE TITLE
Kap、Lemon、Yate、WPS、BaiduYun、XMind、Xnip、Shadowsocks、Fluent Reader

### ISSUE THREAD

**Issue by Vikingama** [elrumo/macOS_Big_Sur_icons_replacements#452]
### Name of app
Kap、Lemon、Yate、WPS、BaiduYun、XMind、Xnip、Shadowsocks、Fluent Reader
### Website of the app requested
https://getkap.co/
https://lemon.qq.com/
https://2manyrobots.com/yate/
https://mac.wps.cn/
https://pan.baidu.com/
https://www.xmind.cn/
http://zh.xnipapp.com/
https://github.com/shadowsocks/ShadowsocksX-NG
https://github.com/yang991178/fluent-reader

**Comment by loukjltd** [comment]
XMind is up now. More Chinese apps icon are on the way. It'll be quick if I am free. :)
