### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by davidbwaters** [elrumo/macOS_Big_Sur_icons_replacements#46]
I thought posting it here might be easier than a PR and I'm not sure everywhere I would need to add it.  I thought I'd share my Transmission icons.  Feel free to edit.
![Transmission-Alt](https://user-images.githubusercontent.com/5247627/87490353-7ce0b180-c613-11ea-81ce-201a5bf9b7b4.png)
![Transmission](https://user-images.githubusercontent.com/5247627/87490370-84a05600-c613-11ea-8d39-296d73ba0f80.png)
[Uploading Transmission.zip…]()

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Transmission.png?raw=true)" width="500">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Transmission.icns)<br>[Transmission](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Transmission.icns)

Done

They look great! Already added it to the repo, I made some small changes to the shadows, hope you don't mind.

**Comment by davidbwaters** [comment]
Looks awesome, thanks.
