### ISSUE TITLE
To Submit: UberConference

### ISSUE THREAD

**Issue by geoffmyers** [elrumo/macOS_Big_Sur_icons_replacements#475]
### Name of app

UberConference

### Link to download the icons
To remember to submit:
- A low res .png

![UberConference](https://user-images.githubusercontent.com/6236958/93608821-14a6a700-f999-11ea-9184-2d9c73cfe7c8.png)

- A high res .png

![UberConference](https://user-images.githubusercontent.com/6236958/93608841-196b5b00-f999-11ea-938c-dc47d2d6bf38.png)

- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar

[UberConference Icon.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5246057/UberConference.Icon.zip)

**Comment by elrumo** [comment]
Sorry it took me forever, I've been working on a new system that will let anyone submit icons directly from macosicons.com. Hopefully I'll launch it this week. 

Just add the icon.
