### ISSUE TITLE
coconutBattery

### ISSUE THREAD

**Issue by owenfiscus** [elrumo/macOS_Big_Sur_icons_replacements#48]
https://coconut-flavour.com/coconutbattery/

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/coconutBattery.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/coconutBattery.icns)<br>[coconutBattery](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/coconutBattery.icns)

Done
