### ISSUE TITLE
New Amazing MacsFanControl Big Sur Icons!

### ISSUE THREAD

**Issue by Aljarus** [elrumo/macOS_Big_Sur_icons_replacements#493]
Macs Fan Control

**Realistic Default:**
<img width="512" alt="Macs Fan Control Metal Frame Silver" src="https://user-images.githubusercontent.com/69454424/94153482-20083f80-fe7d-11ea-86a7-e82115a54b31.png">

**Realistic Dark:**

<img width="512" alt="Macs Fan Control Metal Frame" src="https://user-images.githubusercontent.com/69454424/94153472-1bdc2200-fe7d-11ea-8040-d0b67f8466b8.png">

**Modernistic:**
<img width="512" alt="Macs Fan Control" src="https://user-images.githubusercontent.com/69454424/94153441-12eb5080-fe7d-11ea-8b44-7ac509a8ca6a.png">

**Comment by elrumo** [comment]
Thanks for the icons and sorry it took me forever, I've been working on a new system that will let anyone submit icons directly from macosicons.com. Hopefully I'll launch it this week. 

Just added the icons :)
