### ISSUE TITLE
CyberDuck

### ISSUE THREAD

**Issue by dsa28s** [elrumo/macOS_Big_Sur_icons_replacements#502]
### Name of app
CyberDuck

### Website of the app requested
https://cyberduck.io/

**Comment by nielskorswagen** [comment]
I've added the icon and you can find it on the website now!

**Comment by dsa28s** [comment]
@nielskorswagen Wow! Awesome!! Thank you!

**Comment by dkocher** [comment]
@nielskorswagen This is quite awesome. I am looking into possibly including this icon as the new default when running on macOS 11. Can you let me know if this artwork is licensed under GPL-3.0 License and what attribution you would like to see as I cannot find your real name.

**Comment by nielskorswagen** [comment]
> @nielskorswagen This is quite awesome. I am looking into possibly including this icon as the new default when running on macOS 11. Can you let me know if this artwork is licensed under GPL-3.0 License and what attribution you would like to see as I cannot find your real name.

Hi, that would be so cool! I've sent you an email (the email you use on Github) with everything you need.
