### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by jun-p** [elrumo/macOS_Big_Sur_icons_replacements#505]
### I really love your work!! So I want to use it on my iphone or ipad. But when i add this icon, icon size is smaller than default ios icon size. Could you make icon fit in to it? Plssss Thank. You

**Comment by elrumo** [comment]
That's because the mac icons have padding between the icon itself and the wall limits. But that's good point, I'll play around with an idea I have to make the icons also work for iOS

**Comment by elrumo** [comment]
I forgot to update this issue, but I updated the website so that it makes an iOS version of all the icons submitted. It's not ideal, but it gets the job done for many icons: https://macosicons.com/
