### ISSUE TITLE
Drama | Icon Request

### ISSUE THREAD

**Issue by fn1y** [elrumo/macOS_Big_Sur_icons_replacements#556]
### Name of app
Drama
### Website of the app requested
[drama.app](https://drama.app
)

Really like this repo of icons! Thank you for making these available, I just wanted one for Drama because I want it on my dock without being the odd one out.

**Comment by elrumo** [comment]
Just made one and uploaded it to the site :)

![Drama app icon](https://raw.githubusercontent.com/elrumo/macOS_Big_Sur_icons_replacements/master/icons/png/low-res/Drama.png)

**Comment by fn1y** [comment]
thank you so much!!!!!
