### ISSUE TITLE
SoundCloud

### ISSUE THREAD

**Issue by jxckcooper** [elrumo/macOS_Big_Sur_icons_replacements#557]
### Name of app
Soundcloud
### Website of the app requested
https://www.soundcloud.com

![E763A441-6BBB-4B5D-9435-78B2421149C6](https://user-images.githubusercontent.com/71857285/95656912-13face00-0b5d-11eb-9609-d99b05377163.jpeg)

**Comment by elrumo** [comment]
Done 👍 

![SoundCloud icon](https://raw.githubusercontent.com/elrumo/macOS_Big_Sur_icons_replacements/master/icons/png/low-res/SoundCloud.png)

**Comment by jxckcooper** [comment]
legend
