### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by lowyiyiu** [elrumo/macOS_Big_Sur_icons_replacements#56]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Dropbox.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Dropbox.icns)<br>[Dropbox](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Dropbox.icns)

 [<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Dropbox_alt.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Dropbox_alt.icns)<br>[Dropbox_alt](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Dropbox_alt.icns)

I made two variants, I prefer the alternative version, but it's a bit different to the current icon.
