### ISSUE TITLE
To Submit: Various + Script

### ISSUE THREAD

**Issue by davidbwaters** [elrumo/macOS_Big_Sur_icons_replacements#560]
I have a few icons I made for myself to share.  Some are lower quality versions I made based on default icons to match the UI.

I also made a script to easily set icons.  Just copy the script and 'fileicon' (included) to the folder where the icons are (make sure icon names match app names exactly), run 'sh script.sh' and type in your password and it will automatically set your app icons.

[Set.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5362810/Set.zip)

**Comment by davidbwaters** [comment]
Hey, I found a bug in the script with apps with spaces and fixed it.  Sorry, I never make bash scripts.  Here is the whole thing updated.

[Set2.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5362954/Set2.zip)

**Comment by davidbwaters** [comment]
A few more (icons only).

[More.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5364169/More.zip)

**Comment by davidbwaters** [comment]
One more tweak.  Here is the script and needed files with an instructional readme.
It now automatically clears the icon cache and restarts the Finder.
Icons need to use same name as applications.
Use how you want.  Credits to iconsur and fileicon.

[script.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5364314/script.zip)

**Comment by elrumo** [comment]
Thanks for taking the time to make them! I'll add them first thing tomorrow morning.

**Comment by elrumo** [comment]
Sorry it took me so long, I've been working on a new system that will let anyone submit icons directly from macosicons.com. Hopefully I'll launch it this week.

Just added the icons :)
