### ISSUE TITLE
RubyMine

### ISSUE THREAD

**Issue by pindab0ter** [elrumo/macOS_Big_Sur_icons_replacements#567]
### Name of app
RubyMine

### Website of the app requested
https://www.jetbrains.com/ruby/

**Comment by pindab0ter** [comment]
@yashrajchhabra You've made amazing JetBrains icons for DataGrip, WebStorm and PyCharm. Would you be able to whip one up for RubyMine as well?

**Comment by yashrajchhabra** [comment]
Thanks @pindab0ter. Yes I can do that.

**Comment by pindab0ter** [comment]
The icon was added when the last comment was posted.
