### ISSUE TITLE
Submitting Many Icons (In HiRes PNG only)

### ISSUE THREAD

**Issue by upintheairsheep** [elrumo/macOS_Big_Sur_icons_replacements#572]
I don’t have a Mac so I can’t convert anything. I have an iPad.

### Name of app

- Dolphin

- Dolphin Alt

- Dolphin Alt2

-Wine
-WineBottler
-Bluestacks
-Undertale
-Parallels Desktop (Windows 10)

-Parallels Desktop (Windows 7)

-Parallels Desktop (Windows XP)

-Parallels Desktop (Windows Vista)

-Google Earth
-Google Earth Alt
### Link to download the icons
To remember to submit:

https://drive.google.com/drive/folders/1-4cXnSZP2cuGx7UdoUtbvq4yn_K4nO8U

- A low res .png
- A high res .png
- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar

**Comment by upintheairsheep** [comment]
I’m sorry I couldn’t convert anything

**Comment by upintheairsheep** [comment]
Can you convert it?

**Comment by elrumo** [comment]
Thanks! Just added them.

If you're using an iPad and you'd like to make more icons, I'd recommend you use [this Figma](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/raw/master/design/Template_App_Icon.fig) file directly from Safari.
