### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by isakdombestein** [elrumo/macOS_Big_Sur_icons_replacements#58]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Xcode.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Xcode.icns)<br>[Xcode](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Xcode.icns)

Here it us, I just used the icon for Xcode 12 Beta and removed the Beta label.
