### ISSUE TITLE
To Submit: Visual Studio Code

### ISSUE THREAD

**Issue by uffou** [elrumo/macOS_Big_Sur_icons_replacements#598]
Visual Studio Code

![code-big](https://user-images.githubusercontent.com/2581788/96681826-8d29ca80-1380-11eb-9753-517c62d2cb29.PNG)
![code-small](https://user-images.githubusercontent.com/2581788/96681830-8ef38e00-1380-11eb-8100-69575402c8f3.PNG)

Link to .icns: https://drive.google.com/file/d/1OmW8T9unWjTFjrh427UP-FaRp-W1eKLz/view?usp=sharing

**Comment by elrumo** [comment]
Thanks for the icon, just aded it :)
