### ISSUE TITLE
Found that the WebStorm icon size is different compare to other icons

### ISSUE THREAD

**Issue by loukjltd** [elrumo/macOS_Big_Sur_icons_replacements#611]
So here is the preview. Look at the WebStorm icon.

<img width="1336" alt="Snipaste_2020-10-23_08-54-10" src="https://user-images.githubusercontent.com/68042025/96944466-6e0c7380-150d-11eb-9575-13ad80661b42.png">

Thanks!

**Comment by loukjltd** [comment]
Uh... I guess I can fix it on my own...

**Comment by artexhibit** [comment]
@loukjltd how did you fix that? Have the same issue with another icon...
