### ISSUE TITLE
Png image & icns missing!

### ISSUE THREAD

**Issue by macwkcom** [elrumo/macOS_Big_Sur_icons_replacements#631]
## Missing png

![image](https://user-images.githubusercontent.com/53843550/97343968-18e0b100-18c3-11eb-943c-3eeb75dc3333.png)

- Dolphin_Alt_3Dolphin_Alt_2.png
- Open_Emu_alt_2.png
- Zotero_alt.png

## Missing Icns

- Dolphin_Alt_3Dolphin_Alt_2.icns
- Open_Emu_alt_2.icns
- Zotero_alt.icns

## Duplicate name in icns.txt

![image](https://user-images.githubusercontent.com/53843550/97342746-94d9f980-18c1-11eb-9a23-f88d0550eb37.png)

**Comment by elrumo** [comment]
I'm closing this issue because we don't use that system anymore.
