### ISSUE TITLE
To Submit: 163 Music

### ISSUE THREAD

**Issue by seanzhang98** [elrumo/macOS_Big_Sur_icons_replacements#636]
### Link to download the icons
<img width="512" alt="163Music_low" src="https://user-images.githubusercontent.com/34902361/97653160-18027780-1a9b-11eb-8339-6facfa141535.png">
<img width="512" alt="163Music_hi" src="https://user-images.githubusercontent.com/34902361/97653169-1c2e9500-1a9b-11eb-8564-fcae75b8048c.png">

https://drive.google.com/file/d/1J4Tx_6pOxFo-8yxoBDUps8KsjwVtF-Bj/view?usp=sharing

**Comment by elrumo** [comment]
I don't have access to the drive, you'll have to make the link open to everyone

**Comment by seanzhang98** [comment]
@elrumo already fix the problem.

**Comment by loukjltd** [comment]
I think NetEase Music would be better...

**Comment by elrumo** [comment]
Closing this, as NetEase Music has already been added
