### ISSUE TITLE
To Submit: Eudic

### ISSUE THREAD

**Issue by seanzhang98** [elrumo/macOS_Big_Sur_icons_replacements#638]
### Link to download the icons
<img width="512" alt="Eudic_low" src="https://user-images.githubusercontent.com/34902361/97653551-ffdf2800-1a9b-11eb-8120-684ff22728b7.png">
<img width="512" alt="Eudic_high" src="https://user-images.githubusercontent.com/34902361/97653561-0372af00-1a9c-11eb-94d7-d3151e388978.png">

https://drive.google.com/file/d/1qz8hw9enIT_mn9OazlDGZiBLoNq_SHOl/view?usp=sharing

**Comment by elrumo** [comment]
Same as your other submission, could you please make the link public? Thanks!
