### ISSUE TITLE
To Submit: Thunder Xunlei

### ISSUE THREAD

**Issue by seanzhang98** [elrumo/macOS_Big_Sur_icons_replacements#639]
### Thunder Xunlei
<img width="512" alt="Thunder_low" src="https://user-images.githubusercontent.com/34902361/97653404-ae369d80-1a9b-11eb-94ff-4d42b27e9dd8.png">
<img width="512" alt="Thunder_high" src="https://user-images.githubusercontent.com/34902361/97653413-b2fb5180-1a9b-11eb-9886-7a3a054375a8.png">
### Link to download the icons
https://drive.google.com/file/d/1sfYtPi7JqmpqSneD4SlyjvLOy_GGFWpx/view?usp=sharing

**Comment by elrumo** [comment]
Same issue with this one

**Comment by elrumo** [comment]
Thanks for the icons, adding them now. Also, I've updated the website so now you can make submissions directly from there: [macosicons.com](macosicons.com)
