### ISSUE TITLE
Pixelmator

### ISSUE THREAD

**Issue by LeoAnotherUser** [elrumo/macOS_Big_Sur_icons_replacements#642]
Pixelmator (not Pixelmator Pro)

https://drive.google.com/file/d/10lxqUq8j9ehY-Bc7X7agHilveV7MsDt4/view?usp=sharing

**Comment by elrumo** [comment]
I can't access, it you need to give me access

**Comment by LeoAnotherUser** [comment]
https://drive.google.com/file/d/10lxqUq8j9ehY-Bc7X7agHilveV7MsDt4/view?usp=sharing

Sorry about that.

**Comment by elrumo** [comment]
No problem, just added them
