### ISSUE TITLE
To Submit: [Picatext]

### ISSUE THREAD

**Issue by LeoAnotherUser** [elrumo/macOS_Big_Sur_icons_replacements#646]
Pixatext Name of app

### Link to download the icons
To remember to submit:
- A low res .png
- A high res .png
- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar
https://drive.google.com/file/d/1rLPBvjAKnEPGI-J6FK8nDPdfzZwKnEIF/view?usp=sharing

**Comment by elrumo** [comment]
Done, just added it to the site. Thanks for the submission!
