### ISSUE TITLE
To Submit: [MAMP & MAMP Pro]

### ISSUE THREAD

**Issue by LeoAnotherUser** [elrumo/macOS_Big_Sur_icons_replacements#650]
https://drive.google.com/file/d/13Ur89wrY_Tw-QmwWinZbUG5OWX-yn0se/view?usp=sharing

**Comment by elrumo** [comment]
Thanks for the icons, just added them. Also, I've updated the website so now you can make submissions directly from there: [macosicons.com](https://macosicons.com/)
