### ISSUE TITLE
To Submit: [baidu cloud drive]

### ISSUE THREAD

**Issue by seanzhang98** [elrumo/macOS_Big_Sur_icons_replacements#652]
### Link to download the icons
<img width="512" alt="baiducloud_low" src="https://user-images.githubusercontent.com/34902361/97653268-55670500-1a9b-11eb-8c48-8f08d01f355f.png">
<img width="512" alt="baiducloud_hi" src="https://user-images.githubusercontent.com/34902361/97653271-58fa8c00-1a9b-11eb-9407-aff6ff75e065.png">

https://drive.google.com/file/d/1jZs3WsD6m5XqVA8OicdGVXAIjJAJwBxs/view?usp=sharing

**Comment by loukjltd** [comment]
Hi, thanks for submitting the icon. But also you need to combine a high-res & low-res png file or your icon won't be shown on the website. Thanks!
By the way, I'm not the administrator. Just a notice so you can make a change. :)

**Comment by seanzhang98** [comment]
@loukjltd Thanks, already uploaded a high-res and low-res image.
