### ISSUE TITLE
QQ icon template is not standard

### ISSUE THREAD

**Issue by LiuZhiYu2991** [elrumo/macOS_Big_Sur_icons_replacements#653]
QQ icon is too large

**Comment by loukjltd** [comment]
Hi there,
Thanks for the feedback. I'm working on the new icon so I hope it can replace the old one. Please focus on the pull request and it may take some days for the Administrator to merge the new one. Thanks for you patience!

**Comment by loukjltd** [comment]
Now the new icon has been merged. Could you please check the directory again? Thanks!

**Comment by Tufy-maker** [comment]
> 现在，新图标已合并。您能再检查一下目录吗？谢谢！

Thank you very much. There are no problems！！！
