### ISSUE TITLE
To Submit: [QQ]

### ISSUE THREAD

**Issue by seanzhang98** [elrumo/macOS_Big_Sur_icons_replacements#660]
### Link to download the icons
<img width="512" alt="high" src="https://user-images.githubusercontent.com/34902361/97803492-dc2b0600-1c84-11eb-937c-b68f4458b78e.png">
<img width="512" alt="low" src="https://user-images.githubusercontent.com/34902361/97803499-dfbe8d00-1c84-11eb-83f2-4c97621f76f8.png">

https://drive.google.com/file/d/1NwBjBNhwAd-_R15QnBM5qj-Ixlcx1cxr/view?usp=sharing

**Comment by elrumo** [comment]
They were just added, thanks!
