### ISSUE TITLE
To Submit: [prime video]

### ISSUE THREAD

**Issue by adrillovi** [elrumo/macOS_Big_Sur_icons_replacements#664]
prime video

![high-res:prime_video](https://user-images.githubusercontent.com/73861595/97936325-75d4df00-1d7b-11eb-942b-5d7454e863ad.png)
![low-res:prime_video](https://user-images.githubusercontent.com/73861595/97936327-779ea280-1d7b-11eb-858f-86a6955acc8c.png)

[prime_video.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5478826/prime_video.icns.zip)

**Comment by elrumo** [comment]
Done, just added it to the site. Thanks for the submission!
