### ISSUE TITLE
To Submit: [Slack Dark]

### ISSUE THREAD

**Issue by FedeGarabello** [elrumo/macOS_Big_Sur_icons_replacements#669]
![slack__dark_high_res](https://user-images.githubusercontent.com/47371780/98052752-c862d980-1e15-11eb-8ea1-27dcbd878fbd.png)
![slack_dark_low_res](https://user-images.githubusercontent.com/47371780/98052754-c9940680-1e15-11eb-91e1-547cf61acd01.png)

**Comment by elrumo** [comment]
Done, just added it to the site. Thanks for the submission!
