### ISSUE TITLE
webstorm's icon is large than other apps.

### ISSUE THREAD

**Issue by bytecho** [elrumo/macOS_Big_Sur_icons_replacements#672]
### rt.
![image](https://user-images.githubusercontent.com/16740582/98067884-85e0e180-1e95-11eb-9759-52e2d7878e30.png)

**Comment by loukjltd** [comment]
Hi there,
Thanks for the feedback. This issue has been fixed since I made a pull request a few day ago. The Administrator has merged the right icon to replace the old one. So could you please check the directory again? Thanks!

**Comment by bytecho** [comment]
> Hi there,
> Thanks for the feedback. This issue has been fixed since I made a pull request a few day ago. The Administrator has merged the right icon to replace the old one. So could you please check the directory again? Thanks!

It's ok now. Thanks for your work.
