### ISSUE TITLE
VLC Media Player

### ISSUE THREAD

**Issue by isakdombestein** [elrumo/macOS_Big_Sur_icons_replacements#72]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/VLC.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/VLC.icns)<br>[VLC](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/VLC.icns)

Done
