### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by diegograziano** [elrumo/macOS_Big_Sur_icons_replacements#76]
Actual: 
![Captura de Pantalla 2020-07-17 a la(s) 17 37 01](https://user-images.githubusercontent.com/18469676/87828828-2910db00-c854-11ea-85aa-def7ed419696.png)

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Brave.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Brave.icns)<br>[Brave](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Brave.icns)

Done
