### ISSUE TITLE
To Submit: 115

### ISSUE THREAD

**Issue by wyk111wyk** [elrumo/macOS_Big_Sur_icons_replacements#773]
### 115.com
To remember to submit:
- A low res .png
- A high res .png
- A .icns file made with [Image2Icon](www.img2icnsapp.com) or similar
[115.icns.zip](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/files/5540051/115.icns.zip)

**Comment by elrumo** [comment]
Hi! Thank you so much for your icon, but I've changed the submission process and now you can submit the .png directly from [macOSicons.com](https://macosicons.com/). Could you please submit the high red .png from there?

Thanks again!
