### ISSUE TITLE
GoLand icon can't be downloaded

### ISSUE THREAD

**Issue by GGorAA** [elrumo/macOS_Big_Sur_icons_replacements#791]
The GoLand icons is a lil broken
![image](https://user-images.githubusercontent.com/61655029/99155404-59606d00-26c0-11eb-8e26-79167b0c3b79.png)

**Comment by elrumo** [comment]
Thanks for letting me know, I'll look into that tomorrow. In the meantime you can download another Goland icon that does seem to work [here](https://storage.googleapis.com/download/storage/v1/b/macos-icons.appspot.com/o/icons_approved%2F1605419495329_IntelliJ_GoLand.icns?generation=1605449986053163&alt=media)
