### ISSUE TITLE
Subler

### ISSUE THREAD

**Issue by joshallen13** [elrumo/macOS_Big_Sur_icons_replacements#800]
### Name of app
Subler

### Website of the app requested
https://subler.org

**Comment by ryboh1** [comment]
What is the issue?

**Comment by joshallen13** [comment]
Looks like someone completed this issue!
<img width="512" alt="Subler" src="https://user-images.githubusercontent.com/33143443/99346231-29e96600-2862-11eb-9d6b-bbe1ca69be73.png">
