### ISSUE TITLE
Texpad

### ISSUE THREAD

**Issue by danielsatanik** [elrumo/macOS_Big_Sur_icons_replacements#817]
### Name of app
Texpad

### Website of the app requested
https://www.texpad.com

Thx a lot

**Comment by avatarneil** [comment]
Dupe of https://github.com/elrumo/macOS_Big_Sur_icons_replacements/issues/794

**Comment by danielsatanik** [comment]
Thx I read the list on the website and on the github readme, so I assumed there was not an issue already. I'll close it then.
