### ISSUE TITLE
Launchbar

### ISSUE THREAD

**Issue by el** [elrumo/macOS_Big_Sur_icons_replacements#846]
### Name of app
Launchbar

### Website of the app requested
https://www.obdev.at/products/launchbar/index.html

### Current icon
<img width="146" alt="image" src="https://user-images.githubusercontent.com/1488164/99388296-6bbbf000-28e6-11eb-869c-9ab3fa04533c.png">

**Comment by el** [comment]
I made a simple icon and submitted it. It has been approved and will be available to download shortly.

**Comment by tshu-w** [comment]
@el I cannot find it currently, is this icons deleted?

**Comment by el** [comment]
No, it is on https://macosicons.com Search for `Launchbar`

**Comment by tshu-w** [comment]
but I cannot download it when I click on it.

**Comment by el** [comment]
Looks like there is an issue @elrumo can you take a look?
Here is the logo anyways...
![Launchbar](https://user-images.githubusercontent.com/1488164/102610881-fcccf380-413e-11eb-9d50-3d43e1890bca.png)
