### ISSUE TITLE
Sequel Pro

### ISSUE THREAD

**Issue by el** [elrumo/macOS_Big_Sur_icons_replacements#847]
### Name of app
Sequel Pro

### Website of the app requested
https://www.sequelpro.com

### Current icon
<img width="136" alt="image" src="https://user-images.githubusercontent.com/1488164/99388469-af165e80-28e6-11eb-8e17-ea20d8fbc52d.png">

**Comment by Shamare** [comment]
+1

**Comment by JordySinke** [comment]
I made a simple icon and submitted it through the website.
