### ISSUE TITLE
Noizio

### ISSUE THREAD

**Issue by UgRoss** [elrumo/macOS_Big_Sur_icons_replacements#852]
### Name of app
**Noizio**

### Website of the app requested
* https://noiz.io/

**Comment by Zaitam** [comment]
Done, tell me if you want me to edit it:
![Noizio](https://user-images.githubusercontent.com/71014214/104114110-5b6d3380-52df-11eb-8959-43779c7aec13.png)

**Comment by UgRoss** [comment]
Looks Great!
Thank you!
