### ISSUE TITLE
Raindrop.io

### ISSUE THREAD

**Issue by RobSjaras** [elrumo/macOS_Big_Sur_icons_replacements#86]
https://raindrop.io/download

Not to be confused with it's macOS App Store (Safari Plugin), this for the Desktop app.

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Raindrop.png?raw=true)" width="150">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Raindrop.icns)<br>[Raindrop](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Raindrop.icns)

I also use Raindrop but as great as it is, there are some things I don't like so for the past few months I've actually been working on building my own bookmarking service. It's currently in a very early stage and many features are currently missing. If you have some time I'd really appreciate some feedback: [webbites.io](https://webbites.io)

**Comment by RobSjaras** [comment]
@elrumo  Ah, that explains the Webbites logo you put up earlier. 

I just signed up and so far it looks great, I love the visual overview it provides.

Also what kind of feedback are we looking for?
