### ISSUE TITLE
Astropad Studio

### ISSUE THREAD

**Issue by RobSjaras** [elrumo/macOS_Big_Sur_icons_replacements#87]
This should be a quick one to complete, only the colours needs to be changed

https://astropad.com/product/studio/

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Astropad.png?raw=true)" width="150">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Astropad.icns)<br>[Astropad](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Astropad.icns)

Already did that one a few days ago, I just haven't added it the readme.md, still need to do that. Enjoy :)

**Comment by RobSjaras** [comment]
@elrumo Ah, I should clarify a bit more. There's Astropad and then also Astropad _Studio_.

Astropad Studio has Black/Red colour scheme instead of Red/White :)

Thanks for the quick response!

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Astropad_Studio.png?raw=true)" width="150">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Astropad_Studio.icns)<br>[Astropad Studio](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Astropad_Studio.icns)

I so do not want to have to pay a monthly subscription for Astropad Studio that I even forgot it existed haha 😅. Here it is anyway.

**Comment by RobSjaras** [comment]
Cheers man, your work is amazing! 😄

**Comment by elrumo** [comment]
Thanks! Glad you like it :)
