### ISSUE TITLE
Edit icon name

### ISSUE THREAD

**Issue by hao36** [elrumo/macOS_Big_Sur_icons_replacements#877]
### Describe your issue here, and if possible, add an image.
Hello, I’m hao t. Due to my lack of experience in submitting icons for the first time, the last name displayed on the website is the complete file name, which is very embarrassing. I also trouble the administrator to remove the label for me and only keep the program name. Thanks.
The first one is PureRef
The second is PixelScheduler
![image](https://user-images.githubusercontent.com/24804109/99775211-e59fe380-2b49-11eb-96d8-6d8a4229ece0.png)
![image](https://user-images.githubusercontent.com/24804109/99775273-fa7c7700-2b49-11eb-8957-e81f81854776.png)

**Comment by elrumo** [comment]
Hi, thanks for submitting! 

That was only a bug that I already fixed, where it let you search for icons that had been submitted but not approved, that's why it wasn't showing any icons.

I also changed the name of your icons. Thanks again!!
