### ISSUE TITLE
How to replace icon in app switcher ?

### ISSUE THREAD

**Issue by bobmoff** [elrumo/macOS_Big_Sur_icons_replacements#892]
I updated the icon in Applications folder, but it doesnt change the icon used in the App switcher or the Dock.

Any idea? 

If you know, you should put it in the "change icon" instructions.

Cheers!

**Comment by JDagsa** [comment]
Try these:

1. Relaunch the dock

```
killall Dock
```

2. Remove and re-add app to Dock.

**Comment by bobmoff** [comment]
Thanks for the fast respons. I didnt have do anything, it solved itself after some minutes. Perhaps some cache thing.
