### ISSUE TITLE
Can't download Android File Transfer icon

### ISSUE THREAD

**Issue by oparisblue** [elrumo/macOS_Big_Sur_icons_replacements#893]
### Describe your issue here, and if possible, add an image.

![](https://i.imgur.com/2WObPm0.png)

While I've had success downloading quite a few other icons from the site, it's not possible to click-to-download the "Android File Transfer" icon by bmFtZQ. Using the web inspector, I can see that no `href` is being added to the `<a>` tag forming the card on the page, while all other surrounding icons do have valid `href`s.

I've tried reloading the page, and also tried scrolling through to find the icon rather than searching (in case that was causing the problem) to no avail.

I then decided to search through the icons folder here on GitHub, and could not find the icon in there, however it is questionable whether this is relevant or not, as I did not spend too long searching, and GitHub truncates the directory --- I'm also not completely sure how icons with the same name are being stored (I could only find 3 of the Discord icons, for example, whereas 7 exist on the site, 5 of which have the same name --- the download links work properly for all of these).

**Comment by elrumo** [comment]
So sorry for the late response, I'm going through open tickets at the moment. Unfortunately, the Android File Transfer icon you mention appears to be among one of the icons that were lost due to the hack.
