### ISSUE TITLE
NextDNS, BetterTouchTool, Keyboard Maestro, Pixelmator, LookUp, Dark Reader, Tweetbot, BBEdit

### ISSUE THREAD

**Issue by gracjankn** [elrumo/macOS_Big_Sur_icons_replacements#91]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Pixelmator_Pro.png?raw=true)" width="150">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Pixelmator_Pro.icns)<br>[Pixelmator Pro](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Pixelmator_Pro.icns)

 Pixelmator Pro is already on the folder, just haven't had time yet to update the list on the Readme.
