### ISSUE TITLE
Brave Browser

### ISSUE THREAD

**Issue by sergiozun** [elrumo/macOS_Big_Sur_icons_replacements#95]

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Brave.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Brave.icns)<br>[Brave](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Brave.icns)

Done
