### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by RobSjaras** [elrumo/macOS_Big_Sur_icons_replacements#98]
https://getdrafts.com

**Comment by elrumo** [comment]
[<img src="https://github.com/elrumo/macOS-Big-Sur-icons-replacements/blob/master/icons/png/Drafts.png?raw=true)" width="100">](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Drafts.icns)<br>[ Drafts ](https://github.com/elrumo/macOS-Big-Sur-icons-replacements/raw/master/icons/Drafts.icns)

Done
