### ISSUE TITLE
GenyMotion

### ISSUE THREAD

**Issue by mongkonsrisin** [elrumo/macOS_Big_Sur_icons_replacements#994]
### Name of app
GenyMotion

### Website of the app requested
https://www.genymotion.com/

**Comment by SetuCoder** [comment]
Hello, I've made a genymotion icon for Big Sur. This is the download link. I've uploaded it to the site but it might take a while to get approved. So here you go :)

https://gofile.io/d/nzT1DJ

**Comment by mongkonsrisin** [comment]
Thank you.
