### ISSUE TITLE
CyberGhost VPN Icon

### ISSUE THREAD

**Issue by Dgram19** [elrumo/macOS_Big_Sur_icons_replacements#999]
### Website of the app requested:     https://www.cyberghostvpn.com/
Thanks

**Comment by Zaitam** [comment]
Done ;) 
![EXPORT ME](https://user-images.githubusercontent.com/71014214/104112957-97020080-52d3-11eb-88db-b8c210d1f21e.png)
tell me if you want me to change anything

**Comment by Dgram19** [comment]
Thanks for your availability and nice job. Thank you again.
